set __fish_initialized 3800
set fish_color_autosuggestion brblack
set fish_color_cancel \x2dr
set fish_color_command normal
set fish_color_comment red
set fish_color_cwd green
set fish_color_cwd_root red
set fish_color_end green
set fish_color_error brred
set fish_color_escape brcyan
set fish_color_history_current \x2d\x2dbold
set fish_color_host normal
set fish_color_host_remote yellow
set fish_color_normal normal
set fish_color_operator brcyan
set fish_color_param cyan
set fish_color_quote yellow
set fish_color_redirection cyan\x1e\x2d\x2dbold
set fish_color_search_match white\x1e\x2d\x2dbackground\x3dbrblack\x1e\x2d\x2dbold
set fish_color_selection white\x1e\x2d\x2dbackground\x3dbrblack\x1e\x2d\x2dbold
set fish_color_status red
set fish_color_user brgreen
set fish_color_valid_path \x2d\x2dunderline
set fish_key_bindings fish_default_key_bindings
set fish_pager_color_background \x1d
set fish_pager_color_completion normal
set fish_pager_color_description yellow\x1e\x2di
set fish_pager_color_prefix normal\x1e\x2d\x2dbold\x1e\x2d\x2dunderline
set fish_pager_color_progress brwhite\x1e\x2d\x2dbackground\x3dcyan\x1e\x2d\x2dbold
set fish_pager_color_secondary_background \x1d
set fish_pager_color_secondary_completion \x1d
set fish_pager_color_secondary_description \x1d
set fish_pager_color_secondary_prefix \x1d
set fish_pager_color_selected_background \x2dr
set fish_pager_color_selected_completion \x1d
set fish_pager_color_selected_description \x1d
set fish_pager_color_selected_prefix \x1d
