# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot = {
    kernelParams = ["mem_sleep_default=deep"];
    # Probably wrong - look into kernel resume devices
    # resumeDevice = "/dev/disk/by-uuid/e0250291-e9ec-469c-9ab8-667fc89bc88d";
    # resumeDevice = "/dev/disk/by-uuid/031C5ED7-B026-4993-B4E0-66BA6E0D31BF";
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/60cd8f88-019c-4ef9-b8bc-6f38a3790a9a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4CC0-DD6E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # swapDevices = [ ];
    swapDevices =
    [
      { device = "/dev/disk/by-uuid/e0250291-e9ec-469c-9ab8-667fc89bc88d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
